//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bets
    {
        public int bet_id { get; set; }
        public Nullable<int> player_id { get; set; }
        public Nullable<int> game_id { get; set; }
        public Nullable<decimal> bet_amount { get; set; }
        public byte[] bet_time { get; set; }
        public string outcome { get; set; }
    
        public virtual Games Games { get; set; }
        public virtual Players Players { get; set; }
    }
}
