//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bonuses
    {
        public int bonus_id { get; set; }
        public Nullable<int> player_id { get; set; }
        public string bonus_type { get; set; }
        public Nullable<decimal> bonus_amount { get; set; }
        public Nullable<System.DateTime> bonus_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
