//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        public int transaction_id { get; set; }
        public Nullable<int> player_id { get; set; }
        public string transaction_type { get; set; }
        public Nullable<decimal> transaction_amount { get; set; }
        public byte[] transaction_time { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
